// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPSGame.Repositories;

namespace RPSGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RPSGame.Models.Comment", b =>
                {
                    b.Property<int>("commentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cheer");

                    b.Property<string>("FromEmail");

                    b.Property<string>("FromName");

                    b.Property<string>("Text");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<int?>("ToUserID");

                    b.HasKey("commentID");

                    b.HasIndex("ToUserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RPSGame.Models.Game", b =>
                {
                    b.Property<int>("gameID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Result");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<int?>("UserID");

                    b.HasKey("gameID");

                    b.HasIndex("UserID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RPSGame.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RPSGame.Models.Comment", b =>
                {
                    b.HasOne("RPSGame.Models.User", "To")
                        .WithMany("Comments")
                        .HasForeignKey("ToUserID");
                });

            modelBuilder.Entity("RPSGame.Models.Game", b =>
                {
                    b.HasOne("RPSGame.Models.User")
                        .WithMany("Games")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
